name: HTML Preview

on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 and generate HTML report
        run: |
          mkdir -p flake8-report
          flake8 --format=html --htmldir=flake8-report || true

      - name: Upload Flake8 HTML report
        uses: actions/upload-artifact@v2
        with:
          name: flake8-report
          path: index.htnl
        if: always()
        
      - name: Preview HTML files
        uses: maxheld83/html-preview@0.5.0
        with:
          html_file: index.html
