name: Java CI

on:
  push:
    branches:
      - test-reporter

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.TOKEN_GITHUB }}
        overwrite-settings: true
        job-status: success

    - name: Build and Test with Maven
      run: mvn clean install || true

    - name: Run Java Program
      run: java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App || true

    - name: Generate JUnit Test Report
      uses: dorny/test-reporter@v1
      with:
        name: JUnit Test Report
        path: target/surefire-reports
        reporter: junit
        path-replace-backslashes: false
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-error: true
        fail-on-empty: true
        only-summary: false
        token: ${{ secrets.TOKEN_GITHUB }}
        run: sudo apt install maven -y
