name: Java CI

on:
  push:
    branches:
      - test-reporter

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven
        run: sudo apt install maven -y

      - name: Compile and test
        run: mvn -B clean test

      - name: Linting with Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: target/site/checkstyle-result.xml

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit & Checkstyle Report
          path: target/surefire-reports
          reporter: junit
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
