name: Python Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=10 --html=pytest_report.html

      - name: Lint code
        run: |
          pip install pylint
          pylint src/math_operations.py || true
          pylint tests/*.py || true

      - name: Publish HTML artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: pytest_report.html

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          ACCESS_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          BRANCH: gh-pages
          FOLDER: .  
          CLEAN: true
