name: Code Analysis

on:
  workflow_dispatch:

jobs:
  analyze_code:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the Python version required for your project

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install flake8  # Install Flake8 for code linting
          # Add other dependencies as needed

      # Run static analysis using Flake8
      - name: Run static analysis
        run: |
          flake8 > flake8-report.html  # Save Flake8 report to an HTML file

      # Deploy HTML report as GitHub Pages
      - name: Deploy HTML report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: .  # Directory containing the HTML report
