name: CI
 
on: 
  workflow_dispatch:
 
jobs:
  lint-and-test:
    runs-on: self-hosted
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install Python
        run: |
          # sudo apt update
          sudo apt install python3
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'
 
      
