name: CI
 
on: 
  workflow_dispatch:
 
jobs:
  lint-and-test:
    runs-on: self-hosted
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Run Flake8
        id: flake8
        run: |
          flake8 src --output-file=flake8-result.txt || true
 
      - name: Count Flake8 warnings
        id: count-warnings
        run: |
          warning_count=$(grep -c '^[0-9]* ' flake8-result.txt || echo 0)
          echo "warning_count=$warning_count" >> $GITHUB_ENV
        continue-on-error: true
 
      - name: Check Flake8 warnings
        run: |
          if [ ${{ env.warning_count }} -gt 10 ]; then
            echo "Too many lint warnings (${{ env.warning_count }}). Failing the job."
            exit 1
          fi
 
      - name: Run tests
        run: |
          mkdir -p test-reports
          pytest --junitxml=test-reports/results.xml
        continue-on-error: true
 
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-reports/results.xml
 
      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: flake8-result.txt
