name: HTML Preview

on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 and generate HTML report
        run: |
          mkdir -p flake8-report
          flake8 --format=html --htmldir=flake8-report || true

      - name: Upload Flake8 HTML report
        uses: actions/upload-artifact@v2
        with:
          name: flake8-report
          path: flake8-report
        if: always()

  visualize:
    runs-on: self-hosted

    steps:
      - name: Download Flake8 HTML report
        uses: actions/download-artifact@v2
        with:
          name: flake8-report
          path: flake8-report

      - name: Visualize Flake8 HTML report
        uses: dorny/reporter@v1
        with:
          path: flake8-report/index.html
