name: HTML Visual Report

on: 
  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 and generate text report
        run: |
          flake8 > flake8-report.txt || true

      - name: Convert Flake8 text report to HTML
        run: |
          awk 'BEGIN { print "<html><body><pre>" } {print} END { print "</pre></body></html>" }' flake8-report.txt > flake8-report.html
          
      - name: Upload Flake8 HTML report
        uses: actions/upload-artifact@v2
        with:
          name: flake8-report
          path: flake8-report.html
        if: always()

  visualize:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Visualize Flake8 HTML report in GitHub Actions
        uses: dorny/test-reporter@v1
        with:
          name: Flake8 Report
          reporter: dotnet-trx
          path: flake8-report.html
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          token: ${{ secrets.TOKEN_GITHUB }}
