name: Long Running Workflow

on: workflow_dispatch

jobs:
  long_running_job:
    runs-on: self-hosted

    steps:
      
      - name: Start long-running step
        run: |
          echo "::group::Long Running Step"
          echo "Step started"
          for i in {1..10}; do
            echo "I am still here - Iteration $i - $(date)"
            echo "Sleep mode for 1 minute - $(date)\n"
            sleep 60 # Sleep for 1 minute
          done
          echo "Step completed"
          echo "::endgroup::"
