name: test-reporter-visual

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        source venv/bin/activate
        flake8 src tests || true

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.xml

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: report.html

    - name: Test Reporter
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Pytest Report
        path: report.xml
        reporter: pytest-junit
        path-replace-backslashes: false
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-error: true
        fail-on-empty: true
        only-summary: false
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
